
insert into Video (ID, Name, GenreID) values (1, 'Crow, The', null, null, 680, 2);
insert into Video (ID, Name, GenreID) values (2, 'Shipwrecked (a.k.a. Haakon Haakonsen)', null, null, 1497, 4);
insert into Video (ID, Name, GenreID) values (3, 'Fahrenhype 9/11', null, null, 4859, 3);
insert into Video (ID, Name, GenreID) values (4, 'Lulu in Berlin', null, null, 1011, 1);
insert into Video (ID, Name, GenreID) values (5, 'Lola Versus', null, null, 2584, 1);
insert into Video (ID, Name, GenreID) values (6, 'Hunchback of Notre Dame, The (Notre Dame de Paris)', null, null, 998, 5);
insert into Video (ID, Name, GenreID) values (7, 'Horrible Way to Die, A ', null, null, 2340, 4);
insert into Video (ID, Name, GenreID) values (8, 'Come Back to Me', null, null, 4340, 4);
insert into Video (ID, Name, GenreID) values (9, 'Crippled Avengers (Can que) (Return of the 5 Deadly Venoms)', null, null, 2109, 3);
insert into Video (ID, Name, GenreID) values (10, 'Couch in New York, A', null, null, 869, 2);
insert into Video (ID, Name, GenreID) values (11, 'March of the Movies (Film Parade, The)', null, null, 1927, 3);
insert into Video (ID, Name, GenreID) values (12, 'Harsh Times', null, null, 816, 5);
insert into Video (ID, Name, GenreID) values (13, 'Order, The', null, null, 120, 1);
insert into Video (ID, Name, GenreID) values (14, 'Entrapment', null, null, 2228, 1);
insert into Video (ID, Name, GenreID) values (15, 'Assassination Tango', null, null, 306, 2);
insert into Video (ID, Name, GenreID) values (16, 'Time of Your Life, The', null, null, 3634, 4);
insert into Video (ID, Name, GenreID) values (17, 'Uncovered', null, null, 784, 3);
insert into Video (ID, Name, GenreID) values (18, 'Benji ', null, null, 4492, 1);
insert into Video (ID, Name, GenreID) values (19, 'Fathers'' Day', null, null, 4393, 5);
insert into Video (ID, Name, GenreID) values (20, 'Between Two Worlds', null, null, 3961, 5);
insert into Video (ID, Name, GenreID) values (21, 'Mary Reilly', null, null, 2753, 4);
insert into Video (ID, Name, GenreID) values (22, 'Net 2.0, The ', null, null, 871, 5);
insert into Video (ID, Name, GenreID) values (23, 'My Flesh and Blood', null, null, 1766, 1);
insert into Video (ID, Name, GenreID) values (24, 'Wild River', null, null, 1835, 4);
insert into Video (ID, Name, GenreID) values (25, 'Brief Interviews with Hideous Men', null, null, 1757, 2);
insert into Video (ID, Name, GenreID) values (26, 'Look Who''s Talking Too', null, null, 112, 1);
insert into Video (ID, Name, GenreID) values (27, 'Babymother', null, null, 2977, 2);
insert into Video (ID, Name, GenreID) values (28, 'Hostile Witness', null, null, 1553, 3);
insert into Video (ID, Name, GenreID) values (29, 'Eaten Alive', null, null, 935, 3);
insert into Video (ID, Name, GenreID) values (30, 'Hour of the Wolf (Vargtimmen)', null, null, 3080, 4);
insert into Video (ID, Name, GenreID) values (31, 'Night to Remember, A', null, null, 2240, 3);
insert into Video (ID, Name, GenreID) values (32, 'Eaux d''artifice', null, null, 2751, 3);
insert into Video (ID, Name, GenreID) values (33, 'Cooking with Stella', null, null, 3592, 3);
insert into Video (ID, Name, GenreID) values (34, 'Mephisto', null, null, 668, 2);
insert into Video (ID, Name, GenreID) values (35, 'Phantom of the Opera, The', null, null, 4608, 5);
insert into Video (ID, Name, GenreID) values (36, 'Ocean Waves (Umi ga kikoeru)', null, null, 1458, 2);
insert into Video (ID, Name, GenreID) values (37, 'Yuki & Nina', null, null, 4174, 1);
insert into Video (ID, Name, GenreID) values (38, 'Dark, The', null, null, 2835, 1);
insert into Video (ID, Name, GenreID) values (39, 'Captive, The (La captive)', null, null, 172, 3);
insert into Video (ID, Name, GenreID) values (40, 'House', null, null, 1953, 1);
insert into Video (ID, Name, GenreID) values (41, 'Neil Young: Heart of Gold', null, null, 3268, 1);
insert into Video (ID, Name, GenreID) values (42, 'Room for Romeo Brass, A', null, null, 2604, 1);
insert into Video (ID, Name, GenreID) values (43, 'Meet Monica Velour', null, null, 2619, 3);
insert into Video (ID, Name, GenreID) values (44, 'Hound of the Baskervilles, The', null, null, 852, 3);
insert into Video (ID, Name, GenreID) values (45, 'Belphecor: Curse of the Mummy (Belphégor - Le fantôme du Louvre)', null, null, 2499, 5);
insert into Video (ID, Name, GenreID) values (46, 'Spies (Spione)', null, null, 3907, 2);
insert into Video (ID, Name, GenreID) values (47, 'Tiger Brigades, The (Les brigades du Tigre)', null, null, 3929, 1);
insert into Video (ID, Name, GenreID) values (48, 'Mr. Nice', null, null, 4173, 2);
insert into Video (ID, Name, GenreID) values (49, 'Kumaré', null, null, 2445, 4);
insert into Video (ID, Name, GenreID) values (50, 'Diary of a Madman', null, null, 1444, 5);
insert into Video (ID, Name, GenreID) values (51, 'Midnight Bayou', null, null, 4773, 5);
insert into Video (ID, Name, GenreID) values (52, 'Tar', null, null, 2445, 5);
insert into Video (ID, Name, GenreID) values (53, 'Life with Mikey', null, null, 2842, 2);
insert into Video (ID, Name, GenreID) values (54, 'True Story of Jesse James, The', null, null, 4926, 5);
insert into Video (ID, Name, GenreID) values (55, 'Truly Human (Et rigtigt menneske)', null, null, 3803, 2);
insert into Video (ID, Name, GenreID) values (56, 'Rocketeer, The', null, null, 978, 4);
insert into Video (ID, Name, GenreID) values (57, 'Twist', null, null, 4454, 2);
insert into Video (ID, Name, GenreID) values (58, 'Macon County Line', null, null, 4939, 5);
insert into Video (ID, Name, GenreID) values (59, 'Rape Me (Baise-moi)', null, null, 1960, 1);
insert into Video (ID, Name, GenreID) values (60, 'Young Einstein', null, null, 831, 3);
insert into Video (ID, Name, GenreID) values (61, 'Jakob the Liar', null, null, 2055, 2);
insert into Video (ID, Name, GenreID) values (62, 'It Conquered the World', null, null, 931, 4);
insert into Video (ID, Name, GenreID) values (63, 'Fuga de cerebros', null, null, 4094, 3);
insert into Video (ID, Name, GenreID) values (64, 'Class of Nuke ''Em High Part II: Subhumanoid Meltdown', null, null, 3513, 2);
insert into Video (ID, Name, GenreID) values (65, 'Fallen Idol, The', null, null, 2947, 3);
insert into Video (ID, Name, GenreID) values (66, 'Tai-Pan', null, null, 2069, 3);
insert into Video (ID, Name, GenreID) values (67, 'Pope of Greenwich Village, The', null, null, 3926, 5);
insert into Video (ID, Name, GenreID) values (68, 'El chocolate del loro', null, null, 288, 3);
insert into Video (ID, Name, GenreID) values (69, 'Slugger''s Wife, The', null, null, 1598, 2);
insert into Video (ID, Name, GenreID) values (70, 'The Golden Voyage of Sinbad', null, null, 3450, 4);
insert into Video (ID, Name, GenreID) values (71, 'Monster That Challenged the World, The', null, null, 2798, 5);
insert into Video (ID, Name, GenreID) values (72, 'Takedown: The DNA of GSP', null, null, 3011, 2);
insert into Video (ID, Name, GenreID) values (73, 'Missing', null, null, 1922, 3);
insert into Video (ID, Name, GenreID) values (74, 'Nocturna', null, null, 2925, 5);
insert into Video (ID, Name, GenreID) values (75, 'Miami Connection', null, null, 4267, 4);
insert into Video (ID, Name, GenreID) values (76, 'Bandidas', null, null, 2845, 4);
insert into Video (ID, Name, GenreID) values (77, 'Winter''s Tale', null, null, 2702, 4);
insert into Video (ID, Name, GenreID) values (78, 'Selfish Giant, The', null, null, 624, 1);
insert into Video (ID, Name, GenreID) values (79, 'Evolution', null, null, 1613, 5);
insert into Video (ID, Name, GenreID) values (80, 'Aprile', null, null, 475, 1);
insert into Video (ID, Name, GenreID) values (81, 'Run of the Country, The', null, null, 297, 2);
insert into Video (ID, Name, GenreID) values (82, 'Isabelle au bois dormant', null, null, 279, 5);
insert into Video (ID, Name, GenreID) values (83, 'Monster', null, null, 4298, 2);
insert into Video (ID, Name, GenreID) values (84, 'Django 2: Django Strikes Again', null, null, 1089, 2);
insert into Video (ID, Name, GenreID) values (85, 'Importance of Being Earnest, The', null, null, 4232, 2);
insert into Video (ID, Name, GenreID) values (86, 'Last Call (Hoogste tijd)', null, null, 3127, 3);
insert into Video (ID, Name, GenreID) values (87, 'The Five Man Army', null, null, 1369, 5);
insert into Video (ID, Name, GenreID) values (88, '21', null, null, 2937, 4);
insert into Video (ID, Name, GenreID) values (89, 'Journey to the Center of the Earth', null, null, 801, 3);
insert into Video (ID, Name, GenreID) values (90, 'I Got Next', null, null, 4836, 3);
insert into Video (ID, Name, GenreID) values (91, 'Bratz: The Movie', null, null, 2658, 3);
insert into Video (ID, Name, GenreID) values (92, 'Two Mrs. Carrolls, The', null, null, 2746, 5);
insert into Video (ID, Name, GenreID) values (93, 'Zach Galifianakis: Live at the Purple Onion', null, null, 688, 4);
insert into Video (ID, Name, GenreID) values (94, 'Storytelling', null, null, 1405, 3);
insert into Video (ID, Name, GenreID) values (95, 'He''s Just Not That Into You', null, null, 1744, 3);
insert into Video (ID, Name, GenreID) values (96, 'Stop-Loss', null, null, 3919, 3);
insert into Video (ID, Name, GenreID) values (97, 'Very Long Engagement, A (Un long dimanche de fiançailles)', null, null, 3210, 1);
insert into Video (ID, Name, GenreID) values (98, 'Domino', null, null, 2390, 1);
insert into Video (ID, Name, GenreID) values (99, 'Garage', null, null, 615, 2);
insert into Video (ID, Name, GenreID) values (100, 'Phil Ochs: There But for Fortune', null, null, 2611, 1);
GO
